### ISSUE TITLE
coord flip legends in coord flip plots

### ISSUE THREAD

**Issue by softloud** [jonocarroll/ggeasy#20]
On the banner on my twitter account (cantabile) I've got a vis where I've coord flipped but the legend didn't. Is there an easy way to do this? Can we manipulate elements of a legend? 

John MacKintosh suggested [this resource](http://www.sthda.com/english/wiki/ggplot2-legend-easy-steps-to-change-the-position-and-the-appearance-of-a-graph-legend-in-r-software). Looks like a good place to get started.

**Comment by jonocarroll** [comment]
Reference: 

![cantabile_banner](https://user-images.githubusercontent.com/9496865/38060785-d07685f6-3333-11e8-9a5e-b7ef459e45f7.jpeg)

Is this a `geom_pointrange()`? I can't see an obvious way to do that, but it's not an unheard of request: https://github.com/tidyverse/ggplot2/issues/1389. The suggestion there is to use `ggstance::pointrangeh()` and avoid the `coord_flip()`.

``` r
library(ggplot2)
library(dplyr)

## example data
df <- data.frame(x = 1:100,
                 group = c(rep(TRUE, 50), rep(FALSE, 50)),
                 v = seq(-4, 4, length.out = 100)) %>%
  mutate(y = tanh(v),
         lower = tanh(v) - 0.2,
         upper = tanh(v) + 0.2)

## vertical pointranges
ggplot(df, aes(x, y, colour = group)) + 
  geom_pointrange(aes(ymin = lower, ymax = upper))
```

![](https://i.imgur.com/6x12T89.png)

``` r
## horizontal pointranges via coord_flip, legend still vertical
ggplot(df, aes(x, y, colour = group)) + 
  geom_pointrange(aes(ymin = lower, ymax = upper)) + 
  coord_flip()
```

![](https://i.imgur.com/cchM6X6.png)

``` r
## horizontal pointrange with legend the right way
ggplot(df, aes(y, x, colour = group)) + 
  ggstance::geom_pointrangeh(aes(xmin = lower, xmax = upper))
```

![](https://i.imgur.com/hQFrELy.png)

If an accessible way to alter the legend line angle comes up then it will fit in fine here. Until then, I think the `ggstance` workaround is the only option. I'm happy for this to be reopened if anyone has an idea.

**Comment by topherhuebel** [comment]
Has this ever been resolved? I have the same problem
![PRSCT_rgs2021-07-07](https://user-images.githubusercontent.com/43896938/124813503-dc3e7c80-df5c-11eb-8ad0-fc1a978952e7.png)

**Comment by tranktle** [comment]
@topherhuebel : please see this toy example. Instead of using coord_flip(), I would change the x and y. 

***Reference:*** [https://ggplot2.tidyverse.org/reference/geom_linerange.html](https://ggplot2.tidyverse.org/reference/geom_linerange.html)

## This is the data

```r
data <- tribble(
  ~Treat, ~Group, ~prop, ~prop_lb, ~prob_up, 
  "T1", "G1", 0.7, 0.5, 0.9, 
  "T1", "G2", 0.3, 0.2, 0.4, 
  "T2", "G1", 0.4, 0.35, 0.45, 
  "T2", "G2", 0.6, 0.55, 0.65
)
```
## If we don't use coord_flip(), we have vertical line and vertical legend figures
```
ggplot(data, 
       aes(Treat, prop, color=Group))+
  geom_linerange(aes( ymin=prop_lb, ymax=prob_up), width=0.2, size=0.5, position = "identity",)+
  labs(title="My title",
       x ='Treatment ', y = 'Event proportion')+
   ylim(-0.01, 1.01)+
   theme(legend.direction='vertical')
```
<img width="525" alt="ver_line_ver_legend" src="https://user-images.githubusercontent.com/45803288/221232663-1d462224-2279-4cc6-8b1b-56b3df1cd00d.png">

## when we use coord_flip(), we have horizontal lines and vertical legend figures

```{r}
ggplot(data, 
       aes(Treat, prop, color=Group))+
  geom_linerange(aes( ymin=prop_lb, ymax=prob_up), width=0.2, size=0.5, position = "identity",)+
  labs(title="My title",
       x ='Treatment ', y = 'Event proportion')+
  ylim(-0.01, 1.01)+
  theme(legend.direction='vertical')+
  coord_flip()
```
<img width="525" alt="hor_line_ver_legend" src="https://user-images.githubusercontent.com/45803288/221232952-94b96dec-0936-41b6-b10c-c25b596808bf.png">



## So, instead of using coord_flip, we would change the role of x and y, we will have horizontal lines and horizontal legend figures

```{r}
ggplot(data, 
       aes(prop, Treat, color=Group))+
  geom_linerange(aes( xmin=prop_lb, xmax=prob_up), width=0.2, size=0.5, position = "identity",)+
 
  labs(title="My title",
       x ='Treatment ', y = 'Event proportion')+
   xlim(-0.01, 1.01)+
   theme(legend.direction='vertical')
```
<img width="525" alt="hor_line_hor_legend" src="https://user-images.githubusercontent.com/45803288/221233063-a1bc2d20-516e-499c-b965-8613a6094165.png">
